Доработки Swarm проекта
NorthGateVologda/NorthGateSwarm pull request #9
Opened 2023-07-05 19:30 UTC by sshiae

2023-07-06 08:14 UTC, olgapshen requested changes
Надо на общем собрании решить тему с сертификатами.

2023-07-06 08:14 UTC, olgapshen commented on frontend/Dockerfile
> +CMD ["npm", "start-ssl"]
https://github.com/NorthGateVologda/NorthGateWeb/issues/8

2023-07-06 08:14 UTC, olgapshen commented on generate-ssl.sh
> +sudo openssl genrsa -out /home/docker_volumes/certs/server.key 2048
Думаю всё же надо будет точно решить что идём до конца и не сдаёмся ни при каких обстоятельствах и заказать TSL сертификат. Это уже надо решать с администрацией. @Malaxov16 @Marwin887

2023-07-06 08:14 UTC, olgapshen commented on postgres/docker-compose.yml
> +      - POSTGRES_DB_FILE=/run/secrets/DATABASE_DB_NAME
Docker секреты это круто!!!

2023-07-06 08:18 UTC, sshiae commented on generate-ssl.sh
> +sudo openssl genrsa -out /home/docker_volumes/certs/server.key 2048
Ну да, пока что я свой кастомный используем, но нужно добиваться покупки

2023-07-06 08:19 UTC, olgapshen commented on generate-ssl.sh
> +sudo openssl genrsa -out /home/docker_volumes/certs/server.key 2048
Так TLS не будет на 443 порту? Как это у нас будет работать то?

2023-07-07 06:46 UTC, merged

2023-07-07 06:47 UTC, olgapshen commented
Вчера даже комп не включила... не заметила. Второй MR с телефона слила.